// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/blushft/strana/platform/store/ent/runtime.go

const (
	Version = "v0.2.7"                                          // Version of ent codegen.
	Sum     = "h1:8aBKtC2cBnjbu2y0LnHHYhfJhWXHVvyCbxtNO6jyBm4=" // Sum of ent codegen.
)
