# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: build
    silent: true
  build:
    cmds:
      - go build -o strana ./cmd/cli/main.go
  docker-build:
    cmds:
      - docker build -t blushft/strana -f ./.docker/Dockerfile .
