// Code generated by entc, DO NOT EDIT.

package appstat

const (
	// Label holds the string label denoting the appstat type in the database.
	Label = "app_stat"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPageviews holds the string denoting the pageviews field in the database.
	FieldPageviews = "pageviews"
	// FieldVisitors holds the string denoting the visitors field in the database.
	FieldVisitors = "visitors"
	// FieldSessions holds the string denoting the sessions field in the database.
	FieldSessions = "sessions"
	// FieldBouceRate holds the string denoting the bouce_rate field in the database.
	FieldBouceRate = "bouce_rate"
	// FieldKnownDurations holds the string denoting the known_durations field in the database.
	FieldKnownDurations = "known_durations"
	// FieldAvgDuration holds the string denoting the avg_duration field in the database.
	FieldAvgDuration = "avg_duration"
	// FieldDate holds the string denoting the date field in the database.
	FieldDate = "date"

	// EdgeApp holds the string denoting the app edge name in mutations.
	EdgeApp = "app"

	// Table holds the table name of the appstat in the database.
	Table = "app_stats"
	// AppTable is the table the holds the app relation/edge.
	AppTable = "app_stats"
	// AppInverseTable is the table name for the App entity.
	// It exists in this package in order to avoid circular dependency with the "app" package.
	AppInverseTable = "apps"
	// AppColumn is the table column denoting the app relation/edge.
	AppColumn = "app_stats"
)

// Columns holds all SQL columns for appstat fields.
var Columns = []string{
	FieldID,
	FieldPageviews,
	FieldVisitors,
	FieldSessions,
	FieldBouceRate,
	FieldKnownDurations,
	FieldAvgDuration,
	FieldDate,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the AppStat type.
var ForeignKeys = []string{
	"app_stats",
}
