// Code generated by entc, DO NOT EDIT.

package browser

const (
	// Label holds the string label denoting the browser type in the database.
	Label = "browser"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldUseragent holds the string denoting the useragent field in the database.
	FieldUseragent = "useragent"

	// EdgeEvent holds the string denoting the event edge name in mutations.
	EdgeEvent = "event"

	// Table holds the table name of the browser in the database.
	Table = "browsers"
	// EventTable is the table the holds the event relation/edge.
	EventTable = "browsers"
	// EventInverseTable is the table name for the Event entity.
	// It exists in this package in order to avoid circular dependency with the "event" package.
	EventInverseTable = "events"
	// EventColumn is the table column denoting the event relation/edge.
	EventColumn = "event_browser"
)

// Columns holds all SQL columns for browser fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldVersion,
	FieldUseragent,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Browser type.
var ForeignKeys = []string{
	"event_browser",
}
