// Code generated by entc, DO NOT EDIT.

package hostname

const (
	// Label holds the string label denoting the hostname type in the database.
	Label = "hostname"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"

	// EdgePageStats holds the string denoting the page_stats edge name in mutations.
	EdgePageStats = "page_stats"

	// Table holds the table name of the hostname in the database.
	Table = "hostnames"
	// PageStatsTable is the table the holds the page_stats relation/edge.
	PageStatsTable = "page_stats"
	// PageStatsInverseTable is the table name for the PageStat entity.
	// It exists in this package in order to avoid circular dependency with the "pagestat" package.
	PageStatsInverseTable = "page_stats"
	// PageStatsColumn is the table column denoting the page_stats relation/edge.
	PageStatsColumn = "hostname_page_stats"
)

// Columns holds all SQL columns for hostname fields.
var Columns = []string{
	FieldID,
	FieldName,
}
