// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// RawEvent is the predicate function for rawevent builders.
type RawEvent func(*sql.Selector)
