// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Action is the predicate function for action builders.
type Action func(*sql.Selector)

// App is the predicate function for app builders.
type App func(*sql.Selector)

// AppStat is the predicate function for appstat builders.
type AppStat func(*sql.Selector)

// Device is the predicate function for device builders.
type Device func(*sql.Selector)

// Hostname is the predicate function for hostname builders.
type Hostname func(*sql.Selector)

// PageStat is the predicate function for pagestat builders.
type PageStat func(*sql.Selector)

// PageView is the predicate function for pageview builders.
type PageView func(*sql.Selector)

// Pathname is the predicate function for pathname builders.
type Pathname func(*sql.Selector)

// Screen is the predicate function for screen builders.
type Screen func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
