// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/blushft/strana/platform/store/ent/pagestat"
	"github.com/blushft/strana/platform/store/ent/pathname"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// PathnameCreate is the builder for creating a Pathname entity.
type PathnameCreate struct {
	config
	mutation *PathnameMutation
	hooks    []Hook
}

// SetName sets the name field.
func (pc *PathnameCreate) SetName(s string) *PathnameCreate {
	pc.mutation.SetName(s)
	return pc
}

// AddPageStatIDs adds the page_stats edge to PageStat by ids.
func (pc *PathnameCreate) AddPageStatIDs(ids ...int) *PathnameCreate {
	pc.mutation.AddPageStatIDs(ids...)
	return pc
}

// AddPageStats adds the page_stats edges to PageStat.
func (pc *PathnameCreate) AddPageStats(p ...*PageStat) *PathnameCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pc.AddPageStatIDs(ids...)
}

// Mutation returns the PathnameMutation object of the builder.
func (pc *PathnameCreate) Mutation() *PathnameMutation {
	return pc.mutation
}

// Save creates the Pathname in the database.
func (pc *PathnameCreate) Save(ctx context.Context) (*Pathname, error) {
	if _, ok := pc.mutation.Name(); !ok {
		return nil, &ValidationError{Name: "name", err: errors.New("ent: missing required field \"name\"")}
	}
	var (
		err  error
		node *Pathname
	)
	if len(pc.hooks) == 0 {
		node, err = pc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PathnameMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pc.mutation = mutation
			node, err = pc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(pc.hooks) - 1; i >= 0; i-- {
			mut = pc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PathnameCreate) SaveX(ctx context.Context) *Pathname {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pc *PathnameCreate) sqlSave(ctx context.Context) (*Pathname, error) {
	pa, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	pa.ID = int(id)
	return pa, nil
}

func (pc *PathnameCreate) createSpec() (*Pathname, *sqlgraph.CreateSpec) {
	var (
		pa    = &Pathname{config: pc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: pathname.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: pathname.FieldID,
			},
		}
	)
	if value, ok := pc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: pathname.FieldName,
		})
		pa.Name = value
	}
	if nodes := pc.mutation.PageStatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pathname.PageStatsTable,
			Columns: []string{pathname.PageStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: pagestat.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return pa, _spec
}
