name: Go
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: 1.14
        id: go
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Tests
        run: go test -v ./...
